# Generated by Django 6.0.2 on 2026-02-28 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('packs_per_pallet', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=64, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('released', 'Released'), ('bulk', 'Bulk Pick'), ('forward', 'Forward Pick'), ('verify', 'Verify'), ('ready', 'Ready'), ('exception', 'Exception'), ('dispatched', 'Dispatched')], default='released', max_length=20)),
                ('cutoff_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_packs', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='flow.order')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flow.sku')),
            ],
        ),
    ]
